export const ADD_RECIPES = "ADD_RECIPES";
export const RECIPES_LOADING = "RECIPES_LOADING";
export const RECIPES_FAILED = "RECIPES_FAILED";

export const ADD_FAVORITES = "ADD_FAVORITES";
export const FAVORITES_LOADING = "FAVORITES_LOADING";
export const FAVORITES_FAILED = "FAVORITES_FAILED";
export const ADD_FAVORITE = "ADD_FAVORITE";
