export const ADD_RECIPES = "ADD_RECIPES";
export const RECIPES_LOADING = "RECIPES_LOADING";
export const RECIPES_FAILED = "RECIPES_FAILED";

export const ADD_FAVORITES = "ADD_FAVORITES";
export const FAVORITES_LOADING = "FAVORITES_LOADING";
export const FAVORITES_FAILED = "FAVORITES_FAILED";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";

export const ADD_BLOGS = "ADD_BLOGS";
export const BLOGS_LOADING = "BLOGS_LOADING";
export const BLOGS_FAILED = "BLOGS_FAILED";
export const ADD_POST = "ADD_POST";

export const ADD_MEAPLAN = "ADD_MEALPLAN";
export const MEAPLAN_LOADING = "MEALPLAN_LOADING";
export const MEALPLAN_FAILED = "MEALPLAN_FAILED";
